apiVersion: v1
kind: Service
metadata:
  name: example-node-app
  namespace: example-node-app
spec:
  selector:
    app: example-node-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
    